### ISSUE TITLE
Makefile:62: recipe for target '/home/ubuntu/cecho/c_src/cecho.o' failed

### ISSUE THREAD

**Issue by deadjdona** [mazenharake/cecho#16]
:/home/ubuntu/cecho# ./rebar3 compile
===> Verifying dependencies...
===> Compiling cecho
make: Entering directory '/home/ubuntu/cecho/c_src'
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/lib/erlang/erts-8.3.5/include/ -I /usr/lib/erlang/lib/erl_interface-3.9.3/include  -c -o /home/ubuntu/cecho/c_src/cecho.o /home/ubuntu/cecho/c_src/cecho.c
/home/ubuntu/cecho/c_src/cecho.c:35:21: fatal error: ncurses.h: No such file or directory
 #include "ncurses.h"
                     ^
compilation terminated.
Makefile:62: recipe for target '/home/ubuntu/cecho/c_src/cecho.o' failed
make: *** [/home/ubuntu/cecho/c_src/cecho.o] Error 1
make: Leaving directory '/home/ubuntu/cecho/c_src'
===> Hook for compile failed!

**Comment by mazenharake** [comment]
> /home/ubuntu/cecho/c_src/cecho.c:35:21: fatal error: ncurses.h: No such file or directory #include "ncurses.h"

Please install libncurses

**Comment by deadjdona** [comment]
===> Verifying dependencies...

thought this step should verify this

**Comment by mazenharake** [comment]
Oh, I can see why this is confusing. Rebar3 only checks for Erlang dependencies AFAIK and has no understanding of what the C-libraries dependencies are. If you had an erlang library dependency it would fetch it. 

If there is a way to reliably add dependencies to ncurses (ofcourse other than to just fail at compiletime with a pretty explicit error) please let me know, I would happily add it.

**Comment by deadjdona** [comment]
ncurses5-config --version
