### ISSUE TITLE
erl_ddll issue (driver_error - the specified module could not be found)

### ISSUE THREAD

**Issue by Nate-Wilkins** [mazenharake/cecho#17]
I've been getting this error trying to get this module (0.5.1) to work with the latest OTP version (19) 

Just trying to run the `helloworld.escript`

Here's the error I'm getting.

```
=INFO REPORT==== 21-Jan-2018::05:00:02 ===
    application: cecho
    exited: {{driver_error,"The specified module could not be found."},
             {cecho,start,[normal,[]]}}
    type: temporary
escript: exception exit: {noproc,{gen_server,call,
                                    [cecho_srv,{call,3,undefined},infinity]}}
  in function  gen_server:call/3 (gen_server.erl, line 212)
  in call from cecho_example:helloworld/0 (./deps/cecho/_build/default/lib/cecho/src/cecho_example.erl, line 274)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 557)
  in call from escript:interpret/4 (escript.erl, line 787)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 (init.erl, line 1077)
  in call from init:do_boot/3 (init.erl, line 785)
```

I'm very unfamiliar with how `erl_ddll` works but that's what seems to be causing the issue. I've been digging for a while now was hoping that someone else might know what's going on.

**Comment by mazenharake** [comment]
Hi Nate,

Did you build the dll?

/M

**Comment by Nate-Wilkins** [comment]
Hey @mazenharake yeah I was having some issues on windows but of course everything was solved when I switched off. 

Thanks for the help! If anyone else has this issue on windows I'd be curious to see if they figured anything out.
