### ISSUE TITLE
entop-master/cecho-master/c_src/cecho.c:41:10: fatal error: ncurses.h: No such file or directory  #include "ncurses.h"           ^~~~~~~~~~~ compilation terminated.

### ISSUE THREAD

**Issue by rareman99** [mazenharake/cecho#23]
Can't compile.

**Comment by rareman99** [comment]
rebar3 compile
===> Verifying dependencies...
===> Compiling cecho
===> Compiling /entop-master/cecho-master/c_src/cecho.c
===> /entop-master/cecho-master/c_src/cecho.c:41:10: fatal error: ncurses.h: No such file or directory
 #include "ncurses.h"
          ^~~~~~~~~~~
compilation terminated.

**Comment by djnym** [comment]
Do you have ncurses installed?

**Comment by rareman99** [comment]
Yes, here below.

[root@xxx-rhel8 ~]# rpm -qa | grep -i ncurses
ncurses-6.1-7.20180224.el8.x86_64
ncurses-base-6.1-7.20180224.el8.noarch
ncurses-libs-6.1-7.20180224.el8.x86_64

Reference 
OS: RHEL 8.4
Hardware: x86

**Comment by rareman99** [comment]
Hi,
I'm done for entop just install ncurses*

Thanks.

**Comment by djnym** [comment]
Sorry I didn't get back to you sooner.  Hopefully you figured out that you needed ncurses-devel (or whatever package gives you the header file) in order to compile the NIF.   I think that's what you meant by 'ncurses*', but just wanted to follow up in case you had given up.

**Comment by rareman99** [comment]
Hi
Sorry maybe i type it not clear. Here what i done installed packages contains ncurses now it work for erlang but for rabbitmq is  not suite it below.

For package installed
# rpm -qa | grep -i ncurses
ncurses-6.1-7.20180224.el8.x86_64
ncurses-c++-libs-6.1-7.20180224.el8.x86_64
ncurses-compat-libs-6.1-7.20180224.el8.x86_64
ncurses-base-6.1-7.20180224.el8.noarch
ncurses-devel-6.1-7.20180224.el8.x86_64
ncurses-libs-6.1-7.20180224.el8.x86_64
ncurses-libs-6.1-7.20180224.el8.i686
ncurses-term-6.1-7.20180224.el8.noarch
]#
Erlang 
22/10.7.2.1) unix (sunos 5.11.0) CPU:40 SMP +A:1024 +K
Time: 10:02:07, up for 007:16:25:01, 0ms latency, load average: 1.78, 1.76, 1.75
Processes:   4008,  Run Queue:     0,  Reductions:   1415076 namerpcs: 28
Process Memory: 225.7M total (224.5M used)
System Memory: 109.6M (Atom: 1.5M, Binary: 27.6M, Code: 27.1M, ETS: 12.8M)

RabbitMQ
  9           {badfun, 2
                                                       30297           60                             #Fun<error_logger.0.132682287>},
                 6.3          6.0                                                                                                                                   1.7                       19.9        []}             3
                                                         =WARNING REPORT==== 9-Nov-2021::10:06:59.708547 ===
                                                                     59                                     REPORT_CB/1 CRASH: #{args => [cpu_sup,<7501.22298.821>],
    032          rabbit_mgmt_external_stats    "OS_MON (~p          1690              4           23516          2
